bedita/web-tools

src/BaseApplication.php
tests/TestCase/BaseApplicationTest.php

Add `BaseApplication`

---

composer.json
src/ApiClientProvider.php
tests/TestCase/ApiClientProviderTest.php

This PR adds API client log configuration to `ApiClientProvider` singleton.

API Log config

---

README.md
src/View/Helper/WebComponentsHelper.php
tests/TestCase/View/Helper/WebComponentsHelperTest.php

This PR introduces a new helper to handle Custom Elements initialisation with PHP variables bound as properties.

WebComponents helper

---

src/Controller/ApiProxyTrait.php
tests/TestCase/Controller/ApiProxyTraitTest.php
tests/test_app/TestApp/Controller/ApiController.php

2.x - ApiProxyTrait serialize only defined vars

---

src/Controller/ApiProxyTrait.php
tests/TestCase/Controller/ApiProxyTraitTest.php
tests/test_app/TestApp/Controller/ApiController.php

1.x - ApiProxyTrait serialize only defined vars

---

src/Controller/ApiProxyTrait.php
tests/TestCase/Controller/ApiProxyTraitTest.php

1.x - fix mask relationships

---

src/Controller/ApiProxyTrait.php
tests/TestCase/Controller/ApiProxyTraitTest.php

2.x - fix mask relationships

---

composer.json
src/Command/CacheClearallCommand.php
src/Controller/ApiProxyTrait.php
src/Error/ExceptionRenderer.php
src/Identifier/ApiIdentifier.php
src/Plugin.php
src/SingletonTrait.php
src/Utility/Asset/Strategy/EntrypointsStrategy.php
src/Utility/Asset/Strategy/RevManifestStrategy.php
src/View/Helper/HtmlHelper.php
src/View/Helper/WebComponentsHelper.php
src/View/Twig/BeditaTwigExtension.php
src/View/TwigView.php
tests/TestCase/Controller/ApiProxyTraitTest.php
tests/TestCase/Error/ExceptionRendererTest.php
tests/TestCase/Identifier/ApiIdentifierTest.php
tests/TestCase/PluginTest.php
tests/TestCase/Utility/Asset/AssetStrategyTest.php
tests/TestCase/Utility/Asset/Strategy/EntrypointsStrategyTest.php
tests/TestCase/Utility/Asset/Strategy/RevManifestStrategyTest.php
tests/TestCase/Utility/AssetsRevisionsTest.php
tests/TestCase/View/Helper/AssetHelperTest.php
tests/TestCase/View/Helper/HtmlHelperTest.php
tests/TestCase/View/Helper/ThumbHelperTest.php
tests/TestCase/View/Helper/WebComponentsHelperTest.php
tests/bootstrap.php
tests/test_app/TestApp/Application.php
tests/test_app/TestApp/Controller/ApiController.php

Update
```
"cakephp/cakephp": "~4.2.2",,
"cakephp/authentication": "^2.5.0",
"cakephp/twig-view": "^1.2.0"
```

Upgrade to CakePHP 4.2 and other dep

---

.github/workflows/php.yml
src/ApiClientProvider.php

Update github php workflow for composer 2

Update to composer 2

---

src/Controller/Component/ApiFormatterComponent.php
tests/TestCase/Controller/Component/ApiFormatterComponentTest.php

This provides an ApiFormatterComponent with common formatting related methods.
Ref: 
- #38 for master
- #39 for 1.x
- #40 for 2.x

ApiFormatterComponent

---

.travis.yml
src/Controller/Component/ApiFormatterComponent.php
tests/TestCase/Controller/Component/ApiFormatterComponentTest.php

This provides ApiFormatterComponent
Ref: 
- #38 for master
- #39 for 1.x
- #40 for 2.x

ApiFormatterComponent for 1.x

---

src/Controller/Component/ApiCacheComponent.php
tests/TestCase/Controller/Component/ApiCacheComponentTest.php

Add `ApiCacheComponent` who is responsible for caching results of  GET calls of API endpoints.

Add cache capi component

---

.github/workflows/php.yml
composer.json
src/Controller/Component/ApiFormatterComponent.php
tests/TestCase/Controller/Component/ApiFormatterComponentTest.php

This fixes `ApiFormatterComponent::extractFromIncluded` when included data is a 1-1 relationship (i.e. response from `GET /media?include=object`).
Bonus: introduce gh actions for tests

ApiFormatterComponent::extractFromIncluded, when included data is a 1-1 relationship [1.x]

---

src/Controller/Component/ApiCacheComponent.php
tests/TestCase/Controller/Component/ApiCacheComponentTest.php

This PR fixes a problem with API cache `index`: after a cache clear action `index` was updated only in a first call - on subsequent calls other cache items were never added to the index.
Now index is checked and updated if necessary on every call.

Fix API cache index

---

.github/workflows/php.yml
composer.json
src/Auth/ApiAuthenticate.php
src/SingletonTrait.php
src/View/Helper/HtmlHelper.php
src/View/Twig/BeditaTwigExtension.php
src/View/TwigView.php
tests/TestCase/SingletonTraitTest.php
tests/TestCase/View/TwigViewTest.php

This upgrades dependencies in `composer.json`.
`"cakephp/cakephp": "3.10.*"`
Bonus:
- fix phpcs minor issue
- update workflow php to launch checks on workflow files and composer.json changes too

1.x upgrade dependencies

---

.github/workflows/php.yml

This updates php workflow to run on ubuntu 20.04

[3.x] Php workflow - ubuntu 20.04

---

.github/workflows/php.yml

This updates php workflow to run on ubuntu 20.04

[1.x] Php workflow - ubuntu 20.04

---

.github/workflows/php.yml

Use bedita 4.7.0 docker image for php workflow.

BEdita 4.7.0

---

.github/workflows/php.yml
README.md

This updates php workflow to let github action use ubuntu latest version.

Php workflow with ubuntu latest 

---

.github/workflows/release.yml

This introduces release workflow.
When a PR with proper label is merged, a new release is created by this workflow.
Labels:
- `release:major`
- `release:minor`
- `release:patch`

Release workflow in CI [master, 3.x]

---

.github/workflows/php.yml
.scrutinizer.yml
composer.json
src/Plugin.php
src/View/Helper/HtmlHelper.php
tests/TestCase/Controller/Component/ApiFormatterComponentTest.php
tests/TestCase/Identifier/ApiIdentifierTest.php
tests/TestCase/View/Helper/HtmlHelperTest.php

This adds php 8.2 in CI
Bonus: add scrutinizer config, use php 8.2 in scrutinizer run

PHP 8.2 support

---

composer.json

This updates dependencies to use bedita php-sdk v3.1.0

Use bedita php-sdk 3.1.0

---

.github/workflows/release.yml
src/View/Helper/ThumbHelper.php

This fixes a problem in Thumb helper: `"BEdita\SDK\BEditaClient::thumbs(): Argument #1 ($id) must be of type ?int, string given`.

Fix thumb helper
