bedita/web-tools

src/ApiClientProvider.php
In api client, use log from options or from config (if available: use this order - options, config).
=> feat: use config API.log in ApiClient

src/View/Helper/HtmlHelper.php, tests/TestCase/View/Helper/HtmlHelperTest.php
This provides a basic `HtmlHelper` with `title` method (+ test).
Title method returns:
1. `_title` if set
2. `request->params['controller']` (if `request->params['controller']` is not empty, but `request->params['action']` is empty)
3. `request->params['controller'] - request->params['action']` (if `request->params['controller']` is not empty, and `request->params['action']` is not empty)
4. empty string otherwise
=> feat: html helper + test

src/View/Helper/HtmlHelper.php, tests/TestCase/View/Helper/HtmlHelperTest.php
This provides #6 
New methods available in `BEdita\WebTools\View\Helper\HtmlHelper`:
```
public function metaAll(array $data) : string
public function metaDescription($description) : string
public function metaAuthor(?string $creator) : string
public function metaCss(string $docType) : string
public function metaOpenGraph(array $data) : string
public function metaTwitter(array $data) : string
[...]
public function getMeta(array $data, string $field, $defaultVal = null)
```
`BEdita\WebTools\View\Helper\HtmlHelper` initialize uses meta data (if set) from:
- `Configure::read('Meta')` // override defaults
- `$config['meta']` // override defaults and `Meta` from config
Examples of usage:
// 1. using configuration `Meta`
```
Configure::write('Meta', ['author' => 'gustavo']);
[...]
// in twig …
```
=> meta methods in html helper

src/Utility/AssetsRevisions.php, src/View/Helper/AssetHelper.php, src/View/Helper/HtmlHelper.php, tests/TestCase/Utility/AssetsRevisionsTest.php, tests/TestCase/View/Helper/AssetHelperTest.php, tests/TestCase/View/Helper/HtmlHelperTest.php, tests/test_app/config/rev-manifest.json
In this PR:
* `AssetsRevisions` utility class to handle revisions mapping
* `Html::script()` and `Html::css()` call `AssetsRevisions` method in order to find any available revisioned asset, then parent method is invoked
=> Handle assets revisions in `Html` helper

src/Utility/Asset/AssetStrategy.php, src/Utility/Asset/AssetStrategyInterface.php, src/Utility/Asset/Strategy/EntrypointsStrategy.php, src/Utility/Asset/Strategy/RevManifestStrategy.php, src/Utility/AssetsRevisions.php, src/View/Helper/HtmlHelper.php, tests/TestCase/Utility/Asset/AssetStrategyTest.php, tests/TestCase/Utility/Asset/Strategy/EntrypointsStrategyTest.php, tests/TestCase/Utility/Asset/Strategy/RevManifestStrategyTest.php, tests/TestCase/Utility/AssetsRevisionsTest.php, tests/TestCase/View/Helper/AssetHelperTest.php, tests/TestCase/View/Helper/HtmlHelperTest.php, tests/bootstrap.php, tests/test_app/webroot/custom-manifest.json, tests/test_app/webroot/entrypoints.json, tests/test_app/webroot/rev-manifest.json
This PR add a more flexible way to load assets.
For now we have two stategies implemented, one based on `rev-manifest.json` and another based on `entrypoints.json` (see https://symfony.com/doc/current/frontend.html) that for each entrypoint can include  more `js` and `css` assets.
A simple example can be
```json
{
"entrypoints": {
"app": {
"js": [
"/build/runtime.js",
"/build/app.js"
],
"css": [
"/build/app.css"
]
},
"style": {
"js": [
"/build/runtime.js"
],
"css": [
"/build/style.css"
]
}
}
}
```
As you can see for `app` entrypoint more assets must be linked.
Using this strategy you can:
* load all css for a `app` entry: `{{ Html.css('app')}}` loads `/build/app.css`
* load all js for `app` entry: `{{Html.script('app)}}` loads `/build/runtime.js` and `/build/app.js`
* load all assets for …
=> Assets strategies loader

src/View/TwigView.php, tests/TestCase/View/TwigViewTest.php
This PR introduce the way to setup custom Twig environment using a configuration scoped as `Twig`.
By default `strict_variables` is set to `false`.
=> Setup Twig environment via configuration

src/Controller/ApiProxyTrait.php, tests/TestCase/Controller/ApiProxyTraitTest.php, tests/test_app/TestApp/Application.php, tests/test_app/TestApp/Controller/ApiController.php
This PR introduce the `ApiProxyTrait` that used from a controller allow to proxy requests to BE4 API and respond  with its raw response body. 
To avoid exposing BE4 API url the links are masked, replacing it with app url.
=> Add API proxy trait

src/Controller/ApiProxyTrait.php, tests/TestCase/Controller/ApiProxyTraitTest.php, tests/test_app/TestApp/Controller/ApiController.php
Previously to this PR if a controller that uses `ApiProxyTrait` set a variable, it was serialized in json compromising the API response.
=> ApiProxyTrait serialize only defined vars

src/Controller/ApiProxyTrait.php, tests/TestCase/Controller/ApiProxyTraitTest.php
There was a bug requesting single resource/object as `GET /api/users/1`.
In those requests links inside `relationships` were not correctly masked.
This PR fix this behavior and fix unit tests.
=> ApiProxyTrait: fix mask relationships when a single resource is requested

src/View/Helper/ThumbHelper.php, tests/TestCase/View/Helper/ThumbHelperTest.php
This provides a less strict way to use `Thumb::getUrl`: parameter `$image` can be null.
=> feat: thumb getUrl null param

composer.json, phpcs.xml, src/Error/ExceptionRenderer.php, tests/TestCase/Error/ExceptionRendererTest.php
This PR fix a wrong behavior in `ExceptionRenderer` introduced after the upgrade to CakePHP 4.2.
The template used for rendering error was wrong when occurs a `BEditaClientException` because CakePHP `ExceptionRenderer` set the HTTP status code just for `HttpException`. 
Ref: https://book.cakephp.org/4/en/appendices/4-2-migration-guide.html#error 
**Bonus track**
Introduce PHP Code Sniffer configuration that replace the `cs-setup` script.
=> Handle HTTP status code for BEditaClientException

src/Controller/Component/ApiFormatterComponent.php, tests/TestCase/Controller/Component/ApiFormatterComponentTest.php
This fixes `ApiFormatterComponent::extractFromIncluded` when included data is a 1-1 relationship (i.e. response from `GET /media?include=object`).
=> ApiFormatterComponent::extractFromIncluded, when included data is a 1-1 relationship [master, 3.x]

src/View/Twig/BeditaTwigExtension.php, tests/TestCase/View/Twig/BeditaTwigExtensionTest.php, tests/TestCase/View/TwigViewTest.php
This adds function `element` to `BeditaTwigExtension` in 1.x (like https://github.com/cakephp/twig-view/blob/1.x/src/Twig/Extension/ViewExtension.php#L43).
This should help apps that use webtools 1.x to refactor `{% element ...%}` to `{{ element(...) }}` (road to cakephp 4).
=> Twig function element in BeditaTwigExtension

.github/workflows/php.yml, .gitignore, composer.json, phpstan.neon.dist, tests/TestCase/View/Helper/HtmlHelperTest.php
This updates `php` workflow, so that `phpstan` dependency version is used (instead of downloading it with composer, during CI).
This activity in bedita started with https://github.com/bedita/bedita/pull/1889
=> Add phpstan/phpstan 1.5 + fix php workflow

README.md, composer.json, src/Authenticator/OAuth2Authenticator.php, src/Identifier/OAuth2Identifier.php, src/Middleware/OAuth2Middleware.php, tests/TestCase/Authenticator/OAuth2AuthenticatorTest.php, tests/TestCase/Authenticator/TestProvider.php, tests/TestCase/Identifier/OAuth2IdentifierTest.php, tests/TestCase/Middleware/OAuth2MiddlewareTest.php
In this PR a basic OAuth2 authentication flow has been implemented using `cakephp/authentication` plugin and BEdita4/5 API.
Three new classes have been added:
* `OAuth2Authenticator` class to extract information from request and from the selected oauth2 authentication provider 
* `OAuth2Identifier` class to perform login and signup actions via BEdita API 
* `OAuth2Middleware` class to perform redirect to the oauth2 provider when the authorization URL has been made available in the session
=> External OAuth2 provider authentication

composer.json
In this PR some dependencies have been updated via composer: 
* `"bedita/php-sdk": "^2.1.0"` - to deal with the mandatory `grant_type` in `/auth` calls in BEdita 5
* other updates to `"cakephp/twig-view"`,   `"cakephp/cakephp-codesniffer"` and `"phpstan/phpstan"`
=> feat: update dependencies

src/Error/ExceptionRenderer.php, tests/TestCase/Error/ExceptionRendererTest.php
This PR forces a JSON reponse in `ExceptionRenderer` when `application/json` Accept header is set.
Also: `Cake\Error\Renderer\WebExceptionRenderer` is used instead of the deprecated `Cake\Error\ExceptionRenderer`
=> Show JSON error response on `application/json` Accept

src/Identifier/ApiIdentifier.php, src/Identifier/OAuth2Identifier.php, tests/TestCase/Identifier/OAuth2IdentifierTest.php
This PR fixes an inconsistency between `ApiIdentifier` and `OAuth2Identifier` identity array format.
=> Use same `roles` format in `Identifier` response

composer.json, src/Command/CacheClearallCommand.php, tests/TestCase/View/Helper/AssetHelperTest.php, tests/TestCase/View/Helper/ThumbHelperTest.php
This PR adds automated deprecations checks via `PHPstan`  using `phpstan/phpstan-deprecation-rules` 
At the same time:
* `@phpstan-ignore-line` was added in two cases 
* phpunit deprecated `setMethods` has been replaced with `onlyMethods`
=> Add deprecations check

.github/workflows/release.yml
This provides the possibility to create a release using the reusable workflow Release (this is possible after https://github.com/bedita/github-workflows/pull/16).
Usual PR labels still work as expected (on merging PR with release:* labels, Release workflow create the release, the tag, etc.).
=> Manual release with Release workflow 

composer.json, src/Authenticator/OAuth2Authenticator.php, src/Identifier/OAuth2Identifier.php, tests/TestCase/Authenticator/OAuth2AuthenticatorTest.php, tests/TestCase/View/Helper/HtmlHelperTest.php
This PR provides changes to `OAuth2Authenticator` class to support Apple Sign-In process, where:
* a JWT `leeway` configuration may be needed 
* return call from authorization URL is performed via POST
* `id_token` must be used for user verification
=> Handle Apple Sign-In via OAuth2

.github/dependabot.yml, .github/workflows/php.yml, .github/workflows/release.yml
This updates github workflows to use bedita github-workflows v2 and php 8.3.
Bonus: add dependabot config to open automatically PR on action/codecov/docker updates.
=> bedita github-workflows v2 and php 8.3

.github/workflows/php.yml, README.md, composer.json, src/ApiClientProvider.php, src/Command/CacheClearallCommand.php, src/Controller/ApiProxyTrait.php, src/Identifier/ApiIdentifier.php, src/View/Helper/HtmlHelper.php, src/View/TwigView.php, tests/TestCase/ApiClientProviderTest.php, tests/TestCase/Command/CacheClearallCommandTest.php, tests/TestCase/Controller/ApiProxyTraitTest.php, tests/TestCase/Controller/Component/ApiCacheComponentTest.php, tests/TestCase/Controller/Component/ApiFormatterComponentTest.php, tests/TestCase/PluginTest.php, tests/TestCase/View/Helper/WebComponentsHelperTest.php, tests/TestCase/View/Twig/BeditaTwigExtensionTest.php, tests/TestCase/View/TwigViewTest.php
Temporarily using fork `didoda/php-sdk` to test https://github.com/bedita/php-sdk/pull/38
Bonus: add unit tests to reach 100% code coverage
=> Add tests + update dependencies (bedita/php-sdk)

.github/workflows/php.yml, composer.json
This introduces some breaking changes:
- php >= 8.1
- bedita >= 5
- cakephp >= 4.5
=> Prepare major release 5: BEdita 5 only, php >= 8.1, cakephp 4.5

composer.json
This updates dependencies to use `bedita/php-sdk:^4.0.0`.
=> Bump php-sdk to v4

src/Http/BaseClient.php, tests/TestCase/Http/BaseClientTest.php
This provides an utility function `BaseClient`.
=> Abstract http base client

src/Controller/Component/ApiFormatterComponent.php, src/Utility/ApiTools.php, tests/TestCase/Controller/Component/ApiFormatterComponentTest.php, tests/TestCase/Utility/ApiToolsTest.php
This provides:
- a new method `cleanResponse` in `ApiFormatterComponent`
- a new utility class `ApiTools` that provides "clean response" methods, reusable elsewhere
=> Api response clean utility

src/Controller/Component/ApiFormatterComponent.php, src/Utility/ApiTools.php, tests/TestCase/Controller/Component/ApiFormatterComponentTest.php, tests/TestCase/Utility/ApiToolsTest.php
This provides a way to remove from response undesidered attributes
=> API formatter clean attributes

src/Authenticator/OAuth2Authenticator.php
This PR fixes an issue with provider username not being cast to string. This caused an error when provider username is e.g. a numeric ID that references the user in a third-party repository.
=> Always cast `provider_username` to string

.github/workflows/release.yml, src/Plugin.php
This is to avoid a `CakeException: "Plugin named Cake\TwigView is already loaded"` on plugin bootstrap, when the app already has "Cake\TwigView".
=> Fix: safely load plugin twig view
